#!/usr/bin/env bash
# Install nginx server and must conatain a page that contains "Hello World"

sudo apt update
sudo apt install nginx -y
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"
sudo service nginx start
