#!/usr/bin/env bash
# Install nginx server and must conatain a page that contains "Hello World"

sudo apt update
sudo apt install nginx -y
sudo echo 'Hello World!' > /var/www/html/index.html
sudo echo "
events {
}

http {
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
    }
}
" > /etc/nginx/sites-available/default
sudo service nginx start
