#!/usr/bin/env bash
# Configure server and redirect

sudo apt update
sudo apt install nginx -y
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
