#!/usr/bin/env bash
# redirecting to anothere page

sudo apt update
sudo apt install nginx -y

sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
