#!/usr/bin/env bash
# redirect to a url

sudo apt update
sudo apt install nginx -y

sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

sudo service nginx start

sudo sed -i '53i\\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
