#!/usr/bin/env bash
# Configure server and redirect and 404

sudo apt update
sudo apt install nginx -y

sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/server {/a \\n    error_page 404 /404.html;' /etc/nginx/nginx.conf

sudo service nginx restart
