#!/usr/bin/env bash
# Configure server and redirect and 404

sudo apt update
sudo apt install nginx -y
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/server {/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
