#!/usr/bin/env bash
# install and configure HAproxy load balancer

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy -y

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 432164-web-01 3.95.32.69:80 check
	server 432164-web-02 54.144.129.181:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
